var files_dup =
[
    [ ".dep.inc", "_8dep_8inc.html", null ],
    [ "clients.c", "clients_8c.html", "clients_8c" ],
    [ "clients.h", "clients_8h.html", "clients_8h" ],
    [ "files.c", "files_8c.html", "files_8c" ],
    [ "files.h", "files_8h.html", "files_8h" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "materials.c", "materials_8c.html", "materials_8c" ],
    [ "materials.h", "materials_8h.html", "materials_8h" ],
    [ "materials_in_product.c", "materials__in__product_8c.html", "materials__in__product_8c" ],
    [ "materials_in_product.h", "materials__in__product_8h.html", null ],
    [ "menus.c", "menus_8c.html", "menus_8c" ],
    [ "menus.h", "menus_8h.html", "menus_8h" ],
    [ "menus_text.h", "menus__text_8h.html", "menus__text_8h" ],
    [ "orders.c", "orders_8c.html", "orders_8c" ],
    [ "orders.h", "orders_8h.html", "orders_8h" ],
    [ "production.c", "production_8c.html", "production_8c" ],
    [ "production.h", "production_8h.html", "production_8h" ],
    [ "products.c", "products_8c.html", "products_8c" ],
    [ "products.h", "products_8h.html", "products_8h" ],
    [ "products_in_order.c", "products__in__order_8c.html", "products__in__order_8c" ],
    [ "products_in_order.h", "products__in__order_8h.html", null ],
    [ "utilities.c", "utilities_8c.html", "utilities_8c" ],
    [ "utilities.h", "utilities_8h.html", "utilities_8h" ]
];